### PR TITLE
RELATED: FET-564 Sonar config v2

### PR DESCRIPTION
**Pull request by ivanmjartan**
---

**Proposed release type:** major|minor|patch (see points 6. - 8. of the [semver spec](https://semver.org/#semantic-versioning-specification-semver))

# PR checklist

- [ ] Change was tested using dev-release in Analytical Designer and Dashboards (if applicable).
- [ ] Change is described in [CHANGELOG.md](../blob/master/CHANGELOG.md).
- [ ] Migration guide (for major update) is written to [CHANGELOG.md](../blob/master/CHANGELOG.md).
- [ ] The proposed release type is appropriate (see the comment in [PR template](../blob/master/.github/pull_request_template.md))

### CODE REVIEW

**Comment by ivanmjartan** [comment]
extended check sonar

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#643](https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/643/))
Covered lines: **86%**, change: **0%**
Covered branches: **78.82%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/644/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-oss-check/197/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/644/ : SUCCESS in 1m 23s

**Comment by yenkins** [comment]
### Sonar scan result
 - 6 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-js-check-extended-sonar-PR423

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-oss-check/198/ : SUCCESS in 5s
- https://checklist.intgdc.com/job/compliance/job/gooddata-js-sonarqube-scan-zuul-el7/9/ : SUCCESS in 1m 03s (non-voting)

**Review by pbenes — APPROVED** [review]

**Comment by yenkins** [comment]
### Sonar scan result
 - 6 CODE_SMELL

More detail, see in https://sonarqube-dev.intgdc.com/dashboard?id=gooddata-js-gate-PR423

**Comment by yenkins** [comment]
## The code coverage is **the same** after your change 🤟
This is a good thing if you are not sure ;)
#### Report (compared to build [#643](https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/643/))
Covered lines: **86%**, change: **0%**
Covered branches: **78.82%**, change: **0%**
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/645/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-fossa-scanning-zuul-el7/25/ : SUCCESS in 1m 47s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-js-merge-compliance-check/152/ : SUCCESS in 20s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/645/ : SUCCESS in 1m 39s
- https://checklist.intgdc.com/job/compliance/job/gooddata-js-sonarqube-scan-zuul-el7/10/ : SUCCESS in 58s (non-voting)

**Pull request merged**
