### PR TITLE
RELATED: CL-11399 Yarn support

### PR DESCRIPTION
**Pull request by crudo**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/366/ : ABORTED in 42m 38s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/131/ : ABORTED in 42m 28s

**Comment by crudo** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/367/ : ABORTED in 3m 52s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/132/ : ABORTED in 2m 59s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/368/ : ABORTED in 3m 55s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/133/ : ABORTED in 2m 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/369/ : SUCCESS in 1m 39s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/134/ : SUCCESS in 59s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-js-merge-compliance-check/10/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/370/ : SUCCESS in 57s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/135/ : SUCCESS in 41s

**Pull request merged**
