### PR TITLE
RELATED: FET-384 Test coverage report to pull request

### PR DESCRIPTION
**Pull request by xMort**
---

**Proposed release type:** major|minor|patch (see points 6. - 8. of the [semver spec](https://semver.org/#semantic-versioning-specification-semver))

# PR checklist

- [ ] Change was tested using dev-release in Analytical Designer and Dashboards (if applicable).
- [ ] Change is described in [CHANGELOG.md](../blob/master/CHANGELOG.md).
- [ ] Migration guide (for major update) is written to [CHANGELOG.md](../blob/master/CHANGELOG.md).
- [ ] The proposed release type is appropriate (see the comment in [PR template](../blob/master/.github/pull_request_template.md))

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-oss-check/153/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/600/ : FAILURE in 3m 07s

**Comment by xMort** [comment]
ok to test

**Comment by yenkins** [comment]
## The code coverage **decreased** with your change 🤕\nConsider an extension of the unit tests covering the changed code, please.\n
#### Report (compared to build [#599](https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/599/))\n
Covered lines: **0.8692%**, change: **0.0001%** \n
Covered branches: **0.7874%**, change: **-0.0007%** (additional 1 branches are not covered)\n
#### Coverage report\n
https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/601/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-oss-check/154/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/601/ : SUCCESS in 41s

**Comment by xMort** [comment]
ok to test

**Comment by yenkins** [comment]
## The code coverage **decreased** with your change 🤕
Consider an extension of the unit tests covering the changed code, please.
#### Report (compared to build [#599](https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/599/))
Covered lines: **0.8692%**, change: **0.0001%**
Covered branches: **0.7874%**, change: **-0.0007%** (additional 1 branches are not covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/602/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-oss-check/155/ : SUCCESS in 3s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/602/ : SUCCESS in 42s

**Pull request closed without merging**
