### PR TITLE
FEATURE: CL-7757 Cobertura reports

### PR DESCRIPTION
**Pull request by crudo**

### CODE REVIEW

**Comment by crudo** [comment]
@akloboucnik  mrk pls

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/GD-JS-Pull-Request/81/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/GD-JS-Pull-Request/82/

**Comment by crudo** [comment]
ok to test

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/GD-JS-Pull-Request/83/

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/GD-JS-Pull-Request/84/

**Pull request merged**
