### PR TITLE
FEATURE: CL-10492 npm shrinkwrap

### PR DESCRIPTION
**Pull request by crudo**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/227/ : FAILURE in 2m 12s

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/228/ : FAILURE in 2m 36s

**Comment by gdgate** [comment]
Build succeeded.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/230/ : SUCCESS in 2m 35s

**Comment by crudo** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/231/ : SUCCESS in 40s

**Pull request merged**
