### PR TITLE
TRIVIAL: Rename package.json script to unify it with other repos

### PR DESCRIPTION
**Pull request by xMort**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-opensource-repository-check/105/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/123/ : SUCCESS in 1m 29s

**Comment by martinmosko** [comment]
Due to https://confluence.intgdc.com/display/pap/Commit+Policy this is TRIVIAL change... please change it :)

**Comment by xMort** [comment]
The name of the commit and pull request has been changed according to the Commit policy :)

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-opensource-repository-check/106/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/124/ : SUCCESS in 1m 44s

**Comment by martinmosko** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-merge-compliance-check/38/ : SUCCESS in 26s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/125/ : SUCCESS in 1m 13s

**Pull request merged**
