### PR TITLE
BUGFIX: CL-9971 Unable to switch to related date

### PR DESCRIPTION
**Pull request by dprentis**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/197/ : FAILURE in 1m 39s

**Comment by gdgate** [comment]
Build succeeded.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/198/ : SUCCESS in 2m 07s

**Comment by gdgate** [comment]
Build succeeded.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/199/ : SUCCESS in 1m 55s

**Comment by vaclavbohac** [comment]
👍

**Pull request merged**
