### PR TITLE
FEATURE: BB-1203 Migrate date filters merging from web client to backend

### PR DESCRIPTION
**Pull request by xMort**
The logic of the date filter merging is moved from frontend to the backend as the backend needs to know which filters were global and which local (measure filters) in order to construct correct MAQL queries.

In addition to that, the backend REST API is versioned now. The original API version 1 still expects the date filters to be merged by the frontend (in order for GoodData.UI SDK to be backward compatible for at least a year) while API version 2 and newer expects the filters in the original buckets as they were set by the user.

When the backend returns X-GDC-DEPRECATED response header, the frontend client will output warning into the browser's console. The header is returned in the case when value sent in the X-GDC-VERSION does not identify the latest REST API version deployed on the backend server.

### CODE REVIEW

**Comment by gdgate** [comment]
Merge Failed.

This change or one of its cross-repo dependencies was unable to be automatically merged with the current state of its repository. Please rebase the change and upload a new patchset.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-opensource-repository-check/111/ : SUCCESS in 13s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/132/ : SUCCESS in 1m 24s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-opensource-repository-check/112/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/133/ : SUCCESS in 47s

**Comment by petrjanu** [comment]
LGTM

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-opensource-repository-check/113/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/134/ : SUCCESS in 2m 47s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-merge-compliance-check/41/ : SUCCESS in 54s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/135/ : SUCCESS in 5m 35s

**Pull request merged**
