### PR TITLE
RELATED: CL-8532 Unified ci scripts

### PR DESCRIPTION
**Pull request by crudo**

### CODE REVIEW

**Comment by crudo** [comment]
Hi @akloboucnik, I did not switch to gruntify-eslint in this repo, because there were like 350 issues when I change only one rule in .eslintrc. I believe it will be best if you do it by yourself :)

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/gooddata-js-pull-request-builder/21/

**Comment by yenkins-admin** [comment]
Test PASSed.
Refer to this link for build results: https://ci.intgdc.com/job/gooddata-js-pull-request-builder/22/

**Comment by yenkins-admin** [comment]
Test FAILed.
Refer to this link for build results: https://ci.intgdc.com/job/gooddata-js-pull-request-builder/25/

**Pull request merged**
