### PR TITLE
FEATURE: ONE-2708 Remove filters which were undocumented and are now removed

### PR DESCRIPTION
**Pull request by pbenes**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/11/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/237/ : FAILURE in 1m 55s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/12/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/238/ : SUCCESS in 58s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/13/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/239/ : SUCCESS in 55s

**Comment by vaclavbohac** [comment]
@pbenes 👍

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/20/ : SUCCESS in 6s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/247/ : SUCCESS in 2m 35s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-js-merge-compliance-check/37/ : SUCCESS in 10s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/262/ : SUCCESS in 2m 27s

**Pull request merged**
