### PR TITLE
RELATED: FET-68 rename pkg to @gooddata/gooddata-js

### PR DESCRIPTION
**Pull request by zbycz**

### CODE REVIEW

**Comment by zbycz** [comment]
extended test

**Comment by gdgate** [comment]
Build succeeded (check-extended pipeline).

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/303/ : SUCCESS in 18s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-docker-el7/273/ : SUCCESS in 3m 30s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/304/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-docker-el7/274/ : SUCCESS in 1m 06s

**Pull request merged**
