### PR TITLE
RELATED: RAIL-2813 bump dependencies

### PR DESCRIPTION
**Pull request by no23reason**
* All the dependencies were bumped to the latest majors.
* Minors were bumped for
  * @gooddata/typings to ensure Compatibility
  * lodash to address security advisory fixed in 4.19.0
  * fetch-cookie as it is 0.x so minor is effectively major here
* `es-promise` was removed as it was not used anywhere.
* Compatibility was checked in changelogs of the packages.
* Code was adapted to changes in RxJS and @gooddata/typings.

---

**Proposed release type:** minor the upgrades do not affect backwards compatibility (see points 6. - 8. of the [semver spec](https://semver.org/#semantic-versioning-specification-semver))

# PR checklist

- [x] Change was tested using dev-release in Analytical Designer and Dashboards (if applicable). It was tested in goodstrap and react-components
- [x] Change is described in [CHANGELOG.md](../blob/master/CHANGELOG.md).
- [x] Migration guide (for major update) is written to [CHANGELOG.md](../blob/master/CHANGELOG.md).
- [x] The proposed release type is appropriate (see the comment in [PR template](../blob/master/.github/pull_request_template.md))

### CODE REVIEW

**Comment by yenkins** [comment]
## The code coverage **decreased** with your change 🤕
Consider an extension of the unit tests covering the changed code, please.
#### Report (compared to build [#624](https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/624/))
Covered lines: **86.15%**, change: **-0.04%** (additional 1 lines are not covered)
Covered branches: **78.79%**, change: **-0.07%** (additional 1 branches are not covered)
#### Coverage report
https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/625/artifact/ci/results/coverage/lcov-report/index.html

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-oss-check/176/ : SUCCESS in 7s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/625/ : SUCCESS in 1m 39s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-oss-check/177/ : SUCCESS in 6s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/626/ : SUCCESS in 1m 03s

**Comment by gdgate** [comment]
Build in pipeline check aborted.

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-oss-check/179/ : SUCCESS in 4s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/628/ : SUCCESS in 1m 02s

**Review by kandl — APPROVED** [review]
LGTM

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://checklist.intgdc.com/job/compliance/job/gooddata-js-fossa-scanning-zuul-el7/22/ : SUCCESS in 1m 53s (non-voting)
- https://checklist.intgdc.com/job/compliance/job/gooddata-js-merge-compliance-check/149/ : SUCCESS in 24s
- https://checklist.intgdc.com/job/client-libs/job/gooddata-js-unit-tests-zuul-docker-el7/629/ : SUCCESS in 1m 28s
- https://checklist.intgdc.com/job/compliance/job/gooddata-js-sonarqube-scan-zuul-el7/1/ : SUCCESS in 55s (non-voting)

**Pull request merged**
