### PR TITLE
RELATED: RAIL-341 add docker .config

### PR DESCRIPTION
**Pull request by langhammerp**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/49/ : SUCCESS in 7s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/289/ : SUCCESS in 1m 55s

**Comment by langhammerp** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/50/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/290/ : SUCCESS in 2m 05s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-docker-el7/1/ : SUCCESS in 2m 13s (non-voting)

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-js-merge-compliance-check/46/ : SUCCESS in 12s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/291/ : SUCCESS in 52s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-docker-el7/2/ : SUCCESS in 4m 10s (non-voting)

**Pull request merged**
