### PR TITLE
RELATED CL-11316: Install SDK dependencies with yarn

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/326/ : SUCCESS in 2m 34s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/91/ : SUCCESS in 2m 17s

**Comment by gdgate** [comment]
Build failed (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/327/ : FAILURE in 1m 02s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/92/ : SUCCESS in 36s

**Comment by vaclavbohac** [comment]
ok to test

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/328/ : SUCCESS in 43s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/93/ : SUCCESS in 1m 27s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/329/ : SUCCESS in 2m 14s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/94/ : SUCCESS in 2m 28s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/330/ : SUCCESS in 2m 28s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/95/ : SUCCESS in 1m 06s

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/331/ : SUCCESS in 2m 00s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/96/ : SUCCESS in 32s

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-js-merge-compliance-check/8/ : SUCCESS in 9s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/332/ : SUCCESS in 2m 17s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/97/ : SUCCESS in 1m 36s

**Pull request merged**
