### PR TITLE
RELATED: CL-10470 Availability by filters

### PR DESCRIPTION
**Pull request by lhorak**

### CODE REVIEW

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/224/ : FAILURE in 1m 49s

**Comment by lhorak** [comment]
ok to test

**Comment by gdgate** [comment]
Build failed.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/225/ : FAILURE in 1m 49s

**Comment by gdgate** [comment]
Build succeeded.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/226/ : SUCCESS in 1m 49s

**Comment by gdgate** [comment]
Build succeeded.

- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul/248/ : SUCCESS in 43s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/13/ : SUCCESS in 1m 27s (non-voting)

**Comment by bredy** [comment]
Looks like this issue had been already fixed in CL-10312.

**Pull request closed without merging**
