### PR TITLE
RELATED: RAIL-203 Simplify getObjectUri

### PR DESCRIPTION
**Pull request by vaclavbohac**

### CODE REVIEW

**Comment by vaclavbohac** [comment]
`2.3.0-vaclavbohac-get-object-uri-2017-08-17T14-39-11-295Z`

**Comment by gdgate** [comment]
Build succeeded (check pipeline).

- https://ci.intgdc.com/job/gooddata-js-opensource-repository-check/5/ : SUCCESS in 8s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/229/ : SUCCESS in 2m 02s

**Comment by vaclavbohac** [comment]
*BC break*

**Comment by gdgate** [comment]
Build succeeded (gate pipeline).

- https://ci.intgdc.com/job/gooddata-js-merge-compliance-check/30/ : SUCCESS in 14s
- https://ci.intgdc.com/job/gooddata-js-unit-tests-zuul-el7/232/ : SUCCESS in 1m 55s

**Pull request merged**
